openapi: 3.0.0
info:
  title: Order Service API
  version: v1
  description: API for managing orders.

paths:
  /:
    get:
      summary: Welcome message
      description: Returns a welcome message for the Order Service API.
      responses:
        '200':
          description: Successful operation
          content:
            text/plain:
              schema:
                type: string
                example: Welcome to Order Service API

  /api/order/find/id/{id}:
    get:
      summary: Find order by ID
      description: Retrieves an order by its ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the order to retrieve
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request (e.g., invalid ID)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Order not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/order/find/owner/id/{id}:
    get:
      summary: Find orders by owner ID
      description: Retrieves orders associated with a specific owner ID.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID of the order owner
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: The total number of orders.
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '400':
          description: Bad request (e.g., invalid ID)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/order/find/owner/login/{owner_login}:
    get:
      summary: Find orders by owner login
      description: Retrieves orders associated with a specific owner login.
      parameters:
        - in: path
          name: owner_login
          schema:
            type: string
          required: true
          description: Login of the order owner
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    description: The total number of orders.
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
        '400':
          description: Bad request (e.g., invalid login)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Owner not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/order/create/:
    post:
      summary: Create a new order
      description: Creates a new order with the provided details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Bad request (e.g., invalid input)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Owner not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier for the order.
        ownerId:
          type: integer
          description: ID of the order owner.
        order_items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
      required:
        - id
        - ownerId
        - order_items
    OrderItem:
      type: object
      properties:
        id_food_item:
          type: integer
          description: ID of the food item.
        quantity:
          type: integer
          description: Quantity of the food item.
        name:
          type: string
          description: Name of the food item.
        img:
          type: string
          description: URL of the food item image.
      required:
        - id_food_item
        - quantity
    CreateOrderRequest:
      type: object
      properties:
        ownerId:
          type: integer
          description: ID of the order owner.
        foodItems:
          type: array
          items:
            $ref: '#/components/schemas/FoodItem'
      required:
        - ownerId
        - foodItems
    FoodItem:
      type: object
      properties:
        id:
          type: integer
          description: ID of the food item.
        quantity:
          type: integer
          description: Quantity of the food item.
      required:
        - id
        - quantity
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message.
